### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by WilliamMartini** [SAP/iot-starterkit#24]
Hello,

I have the problem that I get a 404 error when I want to send messages to the device. All other functions work perfectly.
Thanks for help.

Kind regards,
William
![05-09-2016 12-10-36](https://cloud.githubusercontent.com/assets/9478887/18245349/0225145e-7365-11e6-804e-3e29cd4724a8.png)

**Comment by levinanton** [comment]
Hello William,

I see you have the modified UI. Did you also make custom changes to the Java part? Did you try to fire the HTTP request from IoT MMS Push Service (Sample Client)? What was the result there? It would be also nice to see the logs (of both starterkit and iotmms apps), otherwise it is hard to guess what might went wrong.

Regards,
Anton

**Comment by WilliamMartini** [comment]
Hallo Anton,
Thanks for your fast answer. 
No, I only made some changes to the JavaScript. It also doesn’t work without the changes. When I fire the HTTP request from the Service I don’t get an error. 
These are the default trace log and the HTTP access log of the starter kit:
![iotstarterkit_trace_log](https://cloud.githubusercontent.com/assets/9478887/18251973/b644b062-738c-11e6-8b62-df1e8a525f2a.png)
![iotstarterkit_access_log](https://cloud.githubusercontent.com/assets/9478887/18251979/bb95b8fe-738c-11e6-8959-37caf1ce0fcf.png)

This is the error:
![iotstarterkit_error](https://cloud.githubusercontent.com/assets/9478887/18251967/a8a7a2ca-738c-11e6-8ceb-e607e4935154.png)

This is the HTTP access log of the iotmms
![iotmms_access_log](https://cloud.githubusercontent.com/assets/9478887/18251990/c7397632-738c-11e6-9110-1a5fb195669e.png)

Regards,
William

**Comment by levinanton** [comment]
First two (and 7th) entries from iotmms HTTP log (last screenshot) look strange to me. They are relative to /v1/.. but should be relative to /com.sap.iotservices.mms/.. like all others

This explains why you get 404 (and empty response which causes NPE). 
Not clear why StarterKit UI fires request to wrong endpoint, though.

Can you please make a screenshot or better export your iotmms destination of the starterkit? And also check if you have destinations on "account level" called "iotmms" (HCP Cockpit -> Connectivity -> Destinations)?

**Comment by WilliamMartini** [comment]
#Password=<< Existing password/certificate removed on Export >>
#
#Tue Sep 06 12:50:52 UTC 2016
Description=IoT MMS API
Type=HTTP
Authentication=BasicAuthentication
Name=iotmms
CloudConnectorVersion=2
ProxyType=Internet
URL=https\://iotmmsxxxtrial.hanatrial.ondemand.com/com.sap.iotservices.mms
User=xxx

#Password=<< Existing password/certificate removed on Export >>
#
#Tue Sep 06 12:50:53 UTC 2016
Description=IoT RDMS API
Type=HTTP
Authentication=BasicAuthentication
Name=iotrdms
CloudConnectorVersion=2
ProxyType=Internet
URL=https\://iotrdmsiotservices-xxxtrial.hanatrial.ondemand.com/com.sap.iotservices.dms
User=xxx

And the account level iotmms:
#Password=<< Existing password/certificate removed on Export >>
#
#Tue Sep 06 12:47:50 UTC 2016
Type=HTTP
Authentication=BasicAuthentication
WebIDEUsage=odata_gen
Name=iotmms
WebIDEEnabled=true
CloudConnectorVersion=2
URL=https\://iotmmsxxxrial.hanatrial.ondemand.com/
ProxyType=Internet
User=xxx
WebIDESystem=API

**Comment by levinanton** [comment]
Account level "iotmms" destination is a problem. 

It has higher priority over application level destination (it is also called iotmms) when using Destination API. StarterKit (servlet part) retrieves destination by name and then forwards all HTTP requests from UI to MMS. It assumes that MMS URL in destination contains the context path /com.sap.iotservices.mms but since it works with account level destination (URL there is https://iotmmsxxxrial.hanatrial.ondemand.com/) it forwards everything to a wrong endpoint and gets 404 - not found.

Either remove your account level destination or modify its URL by adding a context path to the end. 

Regards,
Anton

**Comment by WilliamMartini** [comment]
Good to know. I modified the destination and now it works perfectly. 
Thanks a lot!

Regards,
William
