### ISSUE TITLE
I don't have any API for Commands

### ISSUE THREAD

**Issue by farminf** [SAP/iot-starterkit#53]
Hi,

I try to send command from cloud to the gateway but the api for command gives me an error.(even get is  not working)

I guess I don't have the command feature installed on the IoT 4.0 service... is that the case?

**Comment by levinanton** [comment]
Hello, no this is not the case. Commands endpoint is provided under "Devices" functional category. Please check under the API Service [1] of your instance. What exactly error do you get? Be aware, that there is no GET endpoint for sending commands. In order to send a command, HTTP POST has to be used.

Regards,
Anton

[1] https://help.sap.com/viewer/6040fec3f22e4f9b8bf495f3789d66b5/Cloud/en-US/13a82ff42b1e48a59022c7fd20a76335.html

**Comment by farminf** [comment]
Thanks for your prompt response.

I get this error on POST to '/commands'  : "javax.ws.rs.ClientErrorException"
and this is the screenshot of my API Service for device
![screenshot from 2017-10-03 16-48-38](https://user-images.githubusercontent.com/4580370/31131589-db9ffe62-a85a-11e7-8e9f-cf3e5beb51e3.png)

**Comment by levinanton** [comment]
Would it be possible for you to open a customer ticket, providing your instance ID? According to the screenshot, I could guess you are on older version still. Regards, Anton

**Comment by farminf** [comment]
Ah.. ok. Yes I guess we should do that.
But just out of curiosity, do you have a trial account that I can test everything meanwhile we open a ticket?
Thanks,
Farmin

**Comment by farminf** [comment]
BTW the version is : 

SAP Internet of Things Service Cockpit 4.7.1

**Comment by levinanton** [comment]
Ok, then let's continue this discussion once customer incident is open. Issue reporting in here is supposed to be used for problems related to the StarterKit samples.
